networks:
  studyconnect-network:
    external: true

services:
  frontend:
    image: sc-frontend
    networks:
      - studyconnect-network
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8080/api/
    ports:
      - "3000:3000"
    # Ensure the container runs and automatically removes after stopping
    # Alternatively, you can use the `--rm` flag in `docker run` via a script if needed
    restart: unless-stopped  # Optional: ensures the service will restart unless manually stopped