name: Frontend CI/CD

on:
  workflow_call:  # Allows this workflow to be triggered by another workflow
  workflow_dispatch: # enables manual trigger

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push frontend image
        run: |
          docker build -t ghcr.io/studyconnect-zhaw/frontend/staging:latest -f docker/Dockerfile .
          docker push ghcr.io/studyconnect-zhaw/frontend/staging:latest

      - name: Clone StudyConnect-ZHAW GitOps repository
        run: |
          git clone https://github.com/StudyConnect-ZHAW/StudyConnect-ZHAW.git ../gitops-repo
          cd ../gitops-repo
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
  
      - name: Update deployment manifest
        run: |
          sed -i 's|image: ghcr.io/studyconnect-zhaw/frontend/staging:.*|image: ghcr.io/studyconnect-zhaw/frontend/staging:latest|' ../gitops-repo/deployment/frontend/K8s/staging/deployment.yaml

      - name: Commit and push changes
        run: |
          cd ../gitops-repo
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add deployment/frontend/K8s/staging/deployment.yaml
          git commit -m "Update frontend image"
          git push
