name: Deploy Frontend

on:
  workflow_dispatch:  # Allows manual trigger for now

jobs:
  build-and-push-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Set backend API URL for frontend
        run: |
          echo "NEXT_PUBLIC_API_URL=${{ secrets.BACKEND_URL }}" >> $GITHUB_ENV

      - name: Build and push Frontend Docker image
        run: |
          VERSION=${GITHUB_REF#refs/tags/}  # Use the same version tag as the backend
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/frontend
          docker build --build-arg NEXT_PUBLIC_API_URL=${{ secrets.BACKEND_URL }} -t $IMAGE_NAME:$VERSION -f docker/Dockerfile .
          docker push $IMAGE_NAME:$VERSION

      - name: Deploy to Rancher
        run: |
          kubectl set image deployment/frontend frontend=ghcr.io/${{ github.repository_owner }}/frontend:$VERSION
          kubectl set image deployment/backend backend=ghcr.io/${{ github.repository_owner }}/backend:$VERSION